### ISSUE TITLE
Clean-up unnecessary files and directories and trace code

### ISSUE THREAD

**Issue by zajichek** [zajichek/zajichek#7]
There are a number of files and sub-directories throughout the project that came with the original academic template that I no longer need. Need to go through and figure out which files/folders can be removed without changing any functionality. Also, just going through and reconciling the purpose/functionality of various components of the code.

**Comment by zajichek** [comment]
The `R` subdirectory contains two empty R files that show:

```
# An optional custom script to run before Hugo builds your site.
# You can delete it if you do not need it.
```
At this point, don't need to do this so removing the R directory altogether

**Comment by zajichek** [comment]
In `config/_default/languages.yaml`, we specify the default site language with

```
en:
  languageCode: en-us
```

If we want to have a multi-lingual site, you create separate directories within `content` for different site "versions" for different languages. Below gives the example for using Chinese language:

```
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: Chinese website title...
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: 传
        url: '#about'
        weight: 1
```
